app01/urls.py
from django.urls import path
from app01.views import *

urlpatterns = [
    path('', index, name="index"),
    path('create_blog/', create_blog, name="create_blog"),
    path('modify_blog/<int:id>', modify_blog, name="modify_blog"),    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda request: redirect('app01/')),
    path('app01/', include('app01.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app01/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    subject = models.CharField(max_length=45, null=False)
    ctx_text = models.TextField(null=True, blank=True)
    ctx_image = models.ImageField(null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject
    
    class Meta:
        verbose_name = "블로그"

app01/forms.py
from django import forms
from app01.models import *

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['subject', 'ctx_text', 'ctx_image']

        widgets = {
            'subject': forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'제목',
            }),
            'ctx_text': forms.Textarea(attrs={
                'class':'form-control',
                'rows': 10,
                'placeholder':'내용',
            }),
        }
        labels = {
            'subject': '제목',
            'ctx_text': '내용',
            'ctx_image': '이미지',
        }

app01/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator

from app01.forms import *

app_name = "app01"

def index(request):
    page = request.GET.get("page", '1')  # 페이지 정보를 받아오고 없으면 초기값 1
    blog_list = Blog.objects.order_by("-create_date") # order by create_date desc
    paginator = Paginator(blog_list, 10)  # 10개씩
    object_list = paginator.get_page(page)
    context = {"title":"테스트", "object_list":object_list}
    return render(request, "app01/index.html", context)

def create_blog(request):
    if request.method == "GET":
        form = BlogForm()
        context = {"form":form}
        return render(request, "app01/create_blog.html", context)
    elif request.method == "POST":
        form = BlogForm(request.POST)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.save()
            return redirect("app01:index")

def modify_blog(request, id:int):
    blog = Blog.objects.get(id=id)    
    if request.method == "GET":
        form = BlogForm(instance=blog)
        context = {"form":form}
        return render(request, "app01/modify_blog.html", context)
    elif request.method == "POST":
        form = BlogForm(request.POST, instance=blog)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.save()
            return redirect("app01:index")            

app01/templates/app01/create_blog.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">저장하기</button>
</form>
{% endblock %}

app01/templates/app01/index.html
{% extends 'base.html' %}

{% block content %}
안녕하세요!<br>
<div>
    <table>
        <thead>
            <tr>
                <th>번호</th>
                <th>제목</th>                
                <th>작성/수정일시</th>                
            </tr>
        </thead>
        <tbody>
            {% for blog in object_list %}
            <tr>
                <td><a href="{% url 'app01:modify_blog' id=blog.id %}">{{ blog.id }}</a></td>
                <td>{{ blog.subject }}</td>
                <td>{{ blog.modify_date }}</td>                                
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div>
    {% include "pagination.html" %}
    <!-- 페이징처리 끝 -->
    <a href="{% url 'app01:create_blog' %}" class="btn btn-primary">블로그 등록하기</a>
</div>
{% endblock %}

app01/templates/app01/modify_blog.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">저장하기</button>
</form>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'app01/bower_components/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">    
    <title>{{ title }}</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<script type="text/javascript" src="{% static 'app01/bower_components/jquery/dist/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'app01/bower_components/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/pagination.html
<ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if object_list.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ object_list.previous_page_number }}">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
    </li>
    {% endif %}
    <!-- 페이지리스트 -->
    {% for page_number in object_list.paginator.page_range %}
    {% if page_number >= object_list.number|add:-5 and page_number <= object_list.number|add:5 %}        
    {% if page_number == object_list.number %}
    <li class="page-item active" aria-current="page">
        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
    </li>
    {% else %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
    </li>
    {% endif %}
    {% endif %}        
    {% endfor %}
    <!-- 다음페이지 -->
    {% if object_list.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ object_list.next_page_number }}">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
    </li>
    {% endif %}
</ul>